const mongoose = require("mongoose");

const schema = mongoose.model('EmojiSetting', new mongoose.Schema({
  _Id: String,
  Onay: String,
  Ret: String,
  Punish: String,
  Rector: String,
  Timezone: String,
  PinkExc: String,
  Off_Voice: String,
  Off_Headphone: String,
  Off_Text: String,
  Off_Streaming: String,
  Off_Camera: String,
  On_Voice: String,
  On_Headphone: String,
  On_Text: String,
  On_Streaming: String,
  On_Camera: String,
  Jail: String,
  Ban: String,
  Black_Point: String,
  Aqua_Point: String,
  Right: String,
  Left: String,
  Join: String,
  Leave: String,
  Home: String,
  Erkek: String,
  Kız: String,
  Merhaba: String,
  Right_Arrow:String,
  Innocent: String,  
  Suspicious: String,
  Moderator: String,
  Online: String,
  Offline: String,
  Dnd: String,
  İdle: String,
  Welcome: String,
  Afk: String,
  Announcement: String,
  Reply: String,
  Error: String,
  Request: String,
  Application: String,
  Blue_Heart: String,
  Task_One: String,
  Task_Two: String,
  Task_Theree: String,
  Task_Four: String,
  Task_Five: String,
  Matter: String,
  Loading: String,
  Star: String,
  Disconnect: String
}));

module.exports = schema;